# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 893)
        MainWindow.setStyleSheet("background-color: #030612;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weatherFrame = QtWidgets.QFrame(self.centralwidget)
        self.weatherFrame.setGeometry(QtCore.QRect(10, 10, 661, 381))
        self.weatherFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weatherFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.weatherFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.weatherFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.weatherFrame.setObjectName("weatherFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.weatherFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weather = QtWidgets.QVBoxLayout()
        self.weather.setObjectName("weather")
        self.newsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.newsHorizontalLayout.setObjectName("newsHorizontalLayout")
        self.weatherSearchBar = QtWidgets.QLineEdit(self.weatherFrame)
        self.weatherSearchBar.setMinimumSize(QtCore.QSize(230, 25))
        self.weatherSearchBar.setMaximumSize(QtCore.QSize(230, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.weatherSearchBar.setFont(font)
        self.weatherSearchBar.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherSearchBar.setClearButtonEnabled(True)
        self.weatherSearchBar.setObjectName("weatherSearchBar")
        self.newsHorizontalLayout.addWidget(self.weatherSearchBar)
        self.weatherSearchBtn = QtWidgets.QPushButton(self.weatherFrame)
        self.weatherSearchBtn.setMinimumSize(QtCore.QSize(65, 25))
        self.weatherSearchBtn.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.weatherSearchBtn.setFont(font)
        self.weatherSearchBtn.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherSearchBtn.setObjectName("weatherSearchBtn")
        self.newsHorizontalLayout.addWidget(self.weatherSearchBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.newsHorizontalLayout.addItem(spacerItem)
        self.weather.addLayout(self.newsHorizontalLayout)
        self.weatherTodayLayout = QtWidgets.QVBoxLayout()
        self.weatherTodayLayout.setSpacing(10)
        self.weatherTodayLayout.setObjectName("weatherTodayLayout")
        self.weatherToday = QtWidgets.QHBoxLayout()
        self.weatherToday.setObjectName("weatherToday")
        self.weatherCityName = QtWidgets.QLabel(self.weatherFrame)
        self.weatherCityName.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.weatherCityName.setFont(font)
        self.weatherCityName.setStyleSheet("color:white;\n"
"")
        self.weatherCityName.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherCityName.setObjectName("weatherCityName")
        self.weatherToday.addWidget(self.weatherCityName)
        self.weatherTodayIcon = QtWidgets.QLabel(self.weatherFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weatherTodayIcon.sizePolicy().hasHeightForWidth())
        self.weatherTodayIcon.setSizePolicy(sizePolicy)
        self.weatherTodayIcon.setMinimumSize(QtCore.QSize(150, 150))
        self.weatherTodayIcon.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayIcon.setFont(font)
        self.weatherTodayIcon.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayIcon.setObjectName("weatherTodayIcon")
        self.weatherToday.addWidget(self.weatherTodayIcon)
        self.weatherTodayLayout.addLayout(self.weatherToday)
        self.todayWeatherInfo = QtWidgets.QGridLayout()
        self.todayWeatherInfo.setSpacing(10)
        self.todayWeatherInfo.setObjectName("todayWeatherInfo")
        self.weatherTodayWind = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayWind.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayWind.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayWind.setFont(font)
        self.weatherTodayWind.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayWind.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayWind.setObjectName("weatherTodayWind")
        self.todayWeatherInfo.addWidget(self.weatherTodayWind, 0, 2, 1, 1)
        self.weatherTodayVisibility = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayVisibility.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayVisibility.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayVisibility.setFont(font)
        self.weatherTodayVisibility.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayVisibility.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayVisibility.setObjectName("weatherTodayVisibility")
        self.todayWeatherInfo.addWidget(self.weatherTodayVisibility, 0, 4, 1, 1)
        self.weatherTodayPressure = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayPressure.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayPressure.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayPressure.setFont(font)
        self.weatherTodayPressure.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayPressure.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayPressure.setObjectName("weatherTodayPressure")
        self.todayWeatherInfo.addWidget(self.weatherTodayPressure, 0, 5, 1, 1)
        self.weatherTodayHumidity = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayHumidity.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayHumidity.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayHumidity.setFont(font)
        self.weatherTodayHumidity.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayHumidity.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayHumidity.setObjectName("weatherTodayHumidity")
        self.todayWeatherInfo.addWidget(self.weatherTodayHumidity, 0, 3, 1, 1)
        self.weatherTodayTemp = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayTemp.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayTemp.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayTemp.setFont(font)
        self.weatherTodayTemp.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayTemp.setObjectName("weatherTodayTemp")
        self.todayWeatherInfo.addWidget(self.weatherTodayTemp, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.todayWeatherInfo.addItem(spacerItem1, 0, 6, 1, 1)
        self.weatherTodayLayout.addLayout(self.todayWeatherInfo)
        self.weather.addLayout(self.weatherTodayLayout)
        self.verticalLayout.addLayout(self.weather)
        self.exchangeFrame = QtWidgets.QFrame(self.centralwidget)
        self.exchangeFrame.setGeometry(QtCore.QRect(10, 410, 661, 441))
        self.exchangeFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.exchangeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exchangeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exchangeFrame.setObjectName("exchangeFrame")
        self.exchangeToday = QtWidgets.QLabel(self.exchangeFrame)
        self.exchangeToday.setGeometry(QtCore.QRect(10, 50, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeToday.setFont(font)
        self.exchangeToday.setStyleSheet("color: white;\n"
"background-color: #0A0F26;\n"
"")
        self.exchangeToday.setObjectName("exchangeToday")
        self.exchangeCurrChartExch = QtWidgets.QLabel(self.exchangeFrame)
        self.exchangeCurrChartExch.setGeometry(QtCore.QRect(10, 90, 641, 341))
        self.exchangeCurrChartExch.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.exchangeCurrChartExch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exchangeCurrChartExch.setAlignment(QtCore.Qt.AlignCenter)
        self.exchangeCurrChartExch.setObjectName("exchangeCurrChartExch")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.exchangeFrame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 313, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.exchangeHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.exchangeHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.exchangeHorizontalLayout.setObjectName("exchangeHorizontalLayout")
        self.exchangeSelectCurr = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.exchangeSelectCurr.setMinimumSize(QtCore.QSize(140, 25))
        self.exchangeSelectCurr.setMaximumSize(QtCore.QSize(140, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.exchangeSelectCurr.setFont(font)
        self.exchangeSelectCurr.setStyleSheet("QComboBox {\n"
"    color: white;                /* Kolor tekstu wyświetlanego w polu */\n"
"    background-color: #181C3B;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    background-color: #181C3B;   /* Tło rozwijanej listy */\n"
"    color: white;              /* Kolor tekstu dla wszystkich elementów */\n"
"    selection-background-color: #cce5ff;\n"
"    selection-color: black;     /* Kolor zaznaczonego elementu */\n"
"}\n"
"")
        self.exchangeSelectCurr.setObjectName("exchangeSelectCurr")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeHorizontalLayout.addWidget(self.exchangeSelectCurr)
        self.exchangeShowBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.exchangeShowBtn.setMinimumSize(QtCore.QSize(65, 25))
        self.exchangeShowBtn.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeShowBtn.setFont(font)
        self.exchangeShowBtn.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.exchangeShowBtn.setObjectName("exchangeShowBtn")
        self.exchangeHorizontalLayout.addWidget(self.exchangeShowBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exchangeHorizontalLayout.addItem(spacerItem2)
        self.newsFrame = QtWidgets.QFrame(self.centralwidget)
        self.newsFrame.setGeometry(QtCore.QRect(700, 10, 580, 840))
        self.newsFrame.setMinimumSize(QtCore.QSize(580, 840))
        self.newsFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.newsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newsFrame.setObjectName("newsFrame")
        self.newsPanel = QtWidgets.QFrame(self.newsFrame)
        self.newsPanel.setGeometry(QtCore.QRect(5, 11, 570, 60))
        self.newsPanel.setMinimumSize(QtCore.QSize(570, 60))
        self.newsPanel.setMaximumSize(QtCore.QSize(570, 60))
        self.newsPanel.setStyleSheet("border: 2px solid #181C3B;\n"
"border-radius: 15px;\n"
"background-color: #181C3B;")
        self.newsPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newsPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newsPanel.setObjectName("newsPanel")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.newsPanel)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.newsHorizontalLayout_top = QtWidgets.QHBoxLayout()
        self.newsHorizontalLayout_top.setObjectName("newsHorizontalLayout_top")
        self.newsSelectLabel = QtWidgets.QLabel(self.newsPanel)
        self.newsSelectLabel.setMinimumSize(QtCore.QSize(130, 30))
        self.newsSelectLabel.setMaximumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.newsSelectLabel.setFont(font)
        self.newsSelectLabel.setStyleSheet("color: white;")
        self.newsSelectLabel.setObjectName("newsSelectLabel")
        self.newsHorizontalLayout_top.addWidget(self.newsSelectLabel)
        self.newsCategoryInput = QtWidgets.QComboBox(self.newsPanel)
        self.newsCategoryInput.setMinimumSize(QtCore.QSize(150, 20))
        self.newsCategoryInput.setMaximumSize(QtCore.QSize(150, 20))
        self.newsCategoryInput.setStyleSheet("QComboBox {\n"
"    color: white;                /* Kolor tekstu wyświetlanego w polu */\n"
"    background-color: #181C3B;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    background-color: #181C3B;   /* Tło rozwijanej listy */\n"
"    color: white;              /* Kolor tekstu dla wszystkich elementów */\n"
"    selection-background-color: #cce5ff;\n"
"    selection-color: black;     /* Kolor zaznaczonego elementu */\n"
"}\n"
"")
        self.newsCategoryInput.setObjectName("newsCategoryInput")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsCategoryInput.addItem("")
        self.newsHorizontalLayout_top.addWidget(self.newsCategoryInput)
        self.newsSubmitBtn = QtWidgets.QPushButton(self.newsPanel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.newsSubmitBtn.setFont(font)
        self.newsSubmitBtn.setStyleSheet("background-color:#0A0F26;\n"
"color: white;\n"
"border: 2px solid #0A0F26;\n"
"border-radius: 15px;")
        self.newsSubmitBtn.setObjectName("newsSubmitBtn")
        self.newsHorizontalLayout_top.addWidget(self.newsSubmitBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.newsHorizontalLayout_top.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.newsHorizontalLayout_top)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.newsFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 581, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.newsVerticalLayoutArticles = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.newsVerticalLayoutArticles.setContentsMargins(0, 0, 0, 0)
        self.newsVerticalLayoutArticles.setObjectName("newsVerticalLayoutArticles")
        self.newsScrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.newsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.newsScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.newsScrollArea.setWidgetResizable(True)
        self.newsScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.newsScrollArea.setObjectName("newsScrollArea")
        self.newsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.newsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 575, 745))
        self.newsScrollAreaWidgetContents.setObjectName("newsScrollAreaWidgetContents")
        self.newsArticleFrameTemplate = QtWidgets.QFrame(self.newsScrollAreaWidgetContents)
        self.newsArticleFrameTemplate.setGeometry(QtCore.QRect(10, 10, 550, 120))
        self.newsArticleFrameTemplate.setMinimumSize(QtCore.QSize(480, 120))
        self.newsArticleFrameTemplate.setMaximumSize(QtCore.QSize(550, 120))
        self.newsArticleFrameTemplate.setStyleSheet("border: 2px solid #181C3B;\n"
"border-radius: 15px;\n"
"background-color: #181C3B;")
        self.newsArticleFrameTemplate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newsArticleFrameTemplate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newsArticleFrameTemplate.setObjectName("newsArticleFrameTemplate")
        self.newsArticleImage = QtWidgets.QLabel(self.newsArticleFrameTemplate)
        self.newsArticleImage.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.newsArticleImage.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #181C3B;\n"
"color: white;\n"
"font: 10pt \"Arial\";")
        self.newsArticleImage.setAlignment(QtCore.Qt.AlignCenter)
        self.newsArticleImage.setObjectName("newsArticleImage")
        self.newsArticleTitle = QtWidgets.QLabel(self.newsArticleFrameTemplate)
        self.newsArticleTitle.setGeometry(QtCore.QRect(120, 10, 411, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.newsArticleTitle.setFont(font)
        self.newsArticleTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newsArticleTitle.setStyleSheet("text-decoration: none;\n"
"color: white;\n"
"font: 10pt \"Arial\";\n"
"\n"
"")
        self.newsArticleTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.newsArticleTitle.setWordWrap(True)
        self.newsArticleTitle.setObjectName("newsArticleTitle")
        self.newsArticleSource = QtWidgets.QLabel(self.newsArticleFrameTemplate)
        self.newsArticleSource.setGeometry(QtCore.QRect(120, 100, 201, 16))
        self.newsArticleSource.setStyleSheet("color: grey;")
        self.newsArticleSource.setObjectName("newsArticleSource")
        self.newsScrollArea.setWidget(self.newsScrollAreaWidgetContents)
        self.newsVerticalLayoutArticles.addWidget(self.newsScrollArea)
        self.newsFrame.raise_()
        self.weatherFrame.raise_()
        self.exchangeFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1288, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weatherSearchBar.setPlaceholderText(_translate("MainWindow", "Enter city name..."))
        self.weatherSearchBtn.setText(_translate("MainWindow", "Search"))
        self.weatherCityName.setText(_translate("MainWindow", "CityName"))
        self.weatherTodayIcon.setText(_translate("MainWindow", "Icon"))
        self.weatherTodayWind.setText(_translate("MainWindow", "Wind"))
        self.weatherTodayVisibility.setText(_translate("MainWindow", "Visibility"))
        self.weatherTodayPressure.setText(_translate("MainWindow", "Pressure"))
        self.weatherTodayHumidity.setText(_translate("MainWindow", "Humidity"))
        self.weatherTodayTemp.setText(_translate("MainWindow", "Temp"))
        self.exchangeToday.setText(_translate("MainWindow", "Todays rate:"))
        self.exchangeCurrChartExch.setText(_translate("MainWindow", "Rate chart"))
        self.exchangeSelectCurr.setItemText(0, _translate("MainWindow", "EUR"))
        self.exchangeSelectCurr.setItemText(1, _translate("MainWindow", "USD"))
        self.exchangeSelectCurr.setItemText(2, _translate("MainWindow", "GBP"))
        self.exchangeSelectCurr.setItemText(3, _translate("MainWindow", "AUD"))
        self.exchangeSelectCurr.setItemText(4, _translate("MainWindow", "JPY"))
        self.exchangeShowBtn.setText(_translate("MainWindow", "Show"))
        self.newsSelectLabel.setText(_translate("MainWindow", "Select category: "))
        self.newsCategoryInput.setItemText(0, _translate("MainWindow", "TOP"))
        self.newsCategoryInput.setItemText(1, _translate("MainWindow", "SPORTS"))
        self.newsCategoryInput.setItemText(2, _translate("MainWindow", "WORLD"))
        self.newsCategoryInput.setItemText(3, _translate("MainWindow", "TECHNOLOGY"))
        self.newsCategoryInput.setItemText(4, _translate("MainWindow", "SCIENCE"))
        self.newsCategoryInput.setItemText(5, _translate("MainWindow", "ENTERTAINMENT"))
        self.newsCategoryInput.setItemText(6, _translate("MainWindow", "FOOD"))
        self.newsCategoryInput.setItemText(7, _translate("MainWindow", "POLITICS"))
        self.newsCategoryInput.setItemText(8, _translate("MainWindow", "FASHION"))
        self.newsSubmitBtn.setText(_translate("MainWindow", "Submit"))
        self.newsArticleImage.setText(_translate("MainWindow", "IMAGE"))
        self.newsArticleTitle.setText(_translate("MainWindow", "TITLE: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."))
        self.newsArticleSource.setText(_translate("MainWindow", "SOURCE: Lorem ipsum dolor sit amet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
