# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 0, 1161, 681))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.exchange_box = QtWidgets.QGroupBox(self.widget)
        self.exchange_box.setObjectName("exchange_box")
        self.exchange_select_curr = QtWidgets.QComboBox(self.exchange_box)
        self.exchange_select_curr.setGeometry(QtCore.QRect(10, 20, 191, 22))
        self.exchange_select_curr.setObjectName("exchange_select_curr")
        self.exchange_select_curr.addItem("")
        self.exchange_select_curr.addItem("")
        self.exchange_select_curr.addItem("")
        self.exchange_select_curr.addItem("")
        self.exchange_select_curr.addItem("")
        self.exchange_show_exchange = QtWidgets.QPushButton(self.exchange_box)
        self.exchange_show_exchange.setGeometry(QtCore.QRect(210, 20, 75, 23))
        self.exchange_show_exchange.setObjectName("exchange_show_exchange")
        self.exchange_curr_chart_exch = QtWidgets.QLabel(self.exchange_box)
        self.exchange_curr_chart_exch.setGeometry(QtCore.QRect(30, 70, 531, 251))
        self.exchange_curr_chart_exch.setText("")
        self.exchange_curr_chart_exch.setObjectName("exchange_curr_chart_exch")
        self.exchange_today = QtWidgets.QLabel(self.exchange_box)
        self.exchange_today.setGeometry(QtCore.QRect(10, 50, 211, 16))
        self.exchange_today.setObjectName("exchange_today")
        self.gridLayout.addWidget(self.exchange_box, 1, 0, 1, 1)
        self.news_box = QtWidgets.QGroupBox(self.widget)
        self.news_box.setObjectName("news_box")
        self.gridLayout.addWidget(self.news_box, 0, 1, 2, 1)
        self.weather_box = QtWidgets.QGroupBox(self.widget)
        self.weather_box.setObjectName("weather_box")
        self.weather_search_bar = QtWidgets.QLineEdit(self.weather_box)
        self.weather_search_bar.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.weather_search_bar.setText("")
        self.weather_search_bar.setCursorPosition(0)
        self.weather_search_bar.setClearButtonEnabled(True)
        self.weather_search_bar.setObjectName("weather_search_bar")
        self.weather_search_btn = QtWidgets.QPushButton(self.weather_box)
        self.weather_search_btn.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.weather_search_btn.setObjectName("weather_search_btn")
        self.gridLayout.addWidget(self.weather_box, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exchange_box.setTitle(_translate("MainWindow", "Exchange"))
        self.exchange_select_curr.setItemText(0, _translate("MainWindow", "EUR"))
        self.exchange_select_curr.setItemText(1, _translate("MainWindow", "USD"))
        self.exchange_select_curr.setItemText(2, _translate("MainWindow", "AUD"))
        self.exchange_select_curr.setItemText(3, _translate("MainWindow", "GBP"))
        self.exchange_select_curr.setItemText(4, _translate("MainWindow", "JPY"))
        self.exchange_show_exchange.setText(_translate("MainWindow", "Show"))
        self.exchange_today.setText(_translate("MainWindow", "Todays value: "))
        self.news_box.setTitle(_translate("MainWindow", "News"))
        self.weather_box.setTitle(_translate("MainWindow", "Weather"))
        self.weather_search_bar.setPlaceholderText(_translate("MainWindow", "Enter city name..."))
        self.weather_search_btn.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
