# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 829)
        MainWindow.setStyleSheet("background-color: #010311;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weatherFrame = QtWidgets.QFrame(self.centralwidget)
        self.weatherFrame.setGeometry(QtCore.QRect(10, 10, 521, 341))
        self.weatherFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.weatherFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.weatherFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.weatherFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.weatherFrame.setObjectName("weatherFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.weatherFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weather = QtWidgets.QVBoxLayout()
        self.weather.setObjectName("weather")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weatherSearchBar = QtWidgets.QLineEdit(self.weatherFrame)
        self.weatherSearchBar.setMinimumSize(QtCore.QSize(230, 25))
        self.weatherSearchBar.setMaximumSize(QtCore.QSize(230, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.weatherSearchBar.setFont(font)
        self.weatherSearchBar.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherSearchBar.setClearButtonEnabled(True)
        self.weatherSearchBar.setObjectName("weatherSearchBar")
        self.horizontalLayout.addWidget(self.weatherSearchBar)
        self.weatherSearchBtn = QtWidgets.QPushButton(self.weatherFrame)
        self.weatherSearchBtn.setMinimumSize(QtCore.QSize(65, 25))
        self.weatherSearchBtn.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.weatherSearchBtn.setFont(font)
        self.weatherSearchBtn.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherSearchBtn.setObjectName("weatherSearchBtn")
        self.horizontalLayout.addWidget(self.weatherSearchBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.weather.addLayout(self.horizontalLayout)
        self.weatherToday_2 = QtWidgets.QVBoxLayout()
        self.weatherToday_2.setSpacing(10)
        self.weatherToday_2.setObjectName("weatherToday_2")
        self.weatherToday = QtWidgets.QHBoxLayout()
        self.weatherToday.setObjectName("weatherToday")
        self.weatherTodayIcon = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayIcon.setMinimumSize(QtCore.QSize(150, 150))
        self.weatherTodayIcon.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayIcon.setFont(font)
        self.weatherTodayIcon.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayIcon.setObjectName("weatherTodayIcon")
        self.weatherToday.addWidget(self.weatherTodayIcon)
        self.weatherTodayTemp = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayTemp.setMinimumSize(QtCore.QSize(120, 120))
        self.weatherTodayTemp.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayTemp.setFont(font)
        self.weatherTodayTemp.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayTemp.setObjectName("weatherTodayTemp")
        self.weatherToday.addWidget(self.weatherTodayTemp)
        self.weatherToday_2.addLayout(self.weatherToday)
        self.todayWeatherInfo = QtWidgets.QGridLayout()
        self.todayWeatherInfo.setSpacing(10)
        self.todayWeatherInfo.setObjectName("todayWeatherInfo")
        self.weatherTodayVisibility = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayVisibility.setMinimumSize(QtCore.QSize(110, 110))
        self.weatherTodayVisibility.setMaximumSize(QtCore.QSize(110, 110))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayVisibility.setFont(font)
        self.weatherTodayVisibility.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayVisibility.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayVisibility.setObjectName("weatherTodayVisibility")
        self.todayWeatherInfo.addWidget(self.weatherTodayVisibility, 0, 2, 1, 1)
        self.weatherTodayWind = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayWind.setMinimumSize(QtCore.QSize(110, 110))
        self.weatherTodayWind.setMaximumSize(QtCore.QSize(110, 110))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayWind.setFont(font)
        self.weatherTodayWind.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayWind.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayWind.setObjectName("weatherTodayWind")
        self.todayWeatherInfo.addWidget(self.weatherTodayWind, 0, 0, 1, 1)
        self.weatherTodayHumidity = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayHumidity.setMinimumSize(QtCore.QSize(110, 110))
        self.weatherTodayHumidity.setMaximumSize(QtCore.QSize(110, 110))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayHumidity.setFont(font)
        self.weatherTodayHumidity.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayHumidity.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayHumidity.setObjectName("weatherTodayHumidity")
        self.todayWeatherInfo.addWidget(self.weatherTodayHumidity, 0, 1, 1, 1)
        self.weatherTodayPressure = QtWidgets.QLabel(self.weatherFrame)
        self.weatherTodayPressure.setMinimumSize(QtCore.QSize(110, 110))
        self.weatherTodayPressure.setMaximumSize(QtCore.QSize(110, 110))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.weatherTodayPressure.setFont(font)
        self.weatherTodayPressure.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.weatherTodayPressure.setAlignment(QtCore.Qt.AlignCenter)
        self.weatherTodayPressure.setObjectName("weatherTodayPressure")
        self.todayWeatherInfo.addWidget(self.weatherTodayPressure, 0, 3, 1, 1)
        self.weatherToday_2.addLayout(self.todayWeatherInfo)
        self.weather.addLayout(self.weatherToday_2)
        self.verticalLayout.addLayout(self.weather)
        self.exchangeFrame = QtWidgets.QListView(self.centralwidget)
        self.exchangeFrame.setGeometry(QtCore.QRect(10, 360, 521, 421))
        self.exchangeFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.exchangeFrame.setObjectName("exchangeFrame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 380, 313, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exchangeSelectCurr = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.exchangeSelectCurr.setMinimumSize(QtCore.QSize(140, 25))
        self.exchangeSelectCurr.setMaximumSize(QtCore.QSize(140, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.exchangeSelectCurr.setFont(font)
        self.exchangeSelectCurr.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"")
        self.exchangeSelectCurr.setObjectName("exchangeSelectCurr")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.exchangeSelectCurr.addItem("")
        self.horizontalLayout_3.addWidget(self.exchangeSelectCurr)
        self.exchangeShowBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.exchangeShowBtn.setMinimumSize(QtCore.QSize(65, 25))
        self.exchangeShowBtn.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeShowBtn.setFont(font)
        self.exchangeShowBtn.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.exchangeShowBtn.setObjectName("exchangeShowBtn")
        self.horizontalLayout_3.addWidget(self.exchangeShowBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.exchangeToday = QtWidgets.QLabel(self.centralwidget)
        self.exchangeToday.setGeometry(QtCore.QRect(30, 440, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeToday.setFont(font)
        self.exchangeToday.setStyleSheet("color: white;\n"
"")
        self.exchangeToday.setObjectName("exchangeToday")
        self.exchangeCurrChartExch = QtWidgets.QLabel(self.centralwidget)
        self.exchangeCurrChartExch.setGeometry(QtCore.QRect(30, 520, 481, 241))
        self.exchangeCurrChartExch.setStyleSheet("background-color:#181C3B;\n"
"color: white;\n"
"border: 2px solid #181C3B;\n"
"border-radius: 15px;")
        self.exchangeCurrChartExch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.exchangeCurrChartExch.setAlignment(QtCore.Qt.AlignCenter)
        self.exchangeCurrChartExch.setObjectName("exchangeCurrChartExch")
        self.newsFrame = QtWidgets.QListView(self.centralwidget)
        self.newsFrame.setGeometry(QtCore.QRect(540, 10, 511, 771))
        self.newsFrame.setStyleSheet("border: 2px solid #0A0F26;\n"
"border-radius: 15px;\n"
"background-color: #0A0F26;")
        self.newsFrame.setObjectName("newsFrame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weatherSearchBar.setPlaceholderText(_translate("MainWindow", "Enter city name..."))
        self.weatherSearchBtn.setText(_translate("MainWindow", "Search"))
        self.weatherTodayIcon.setText(_translate("MainWindow", "Icon"))
        self.weatherTodayTemp.setText(_translate("MainWindow", "Temp"))
        self.weatherTodayVisibility.setText(_translate("MainWindow", "Visibility"))
        self.weatherTodayWind.setText(_translate("MainWindow", "Wind"))
        self.weatherTodayHumidity.setText(_translate("MainWindow", "Humidity"))
        self.weatherTodayPressure.setText(_translate("MainWindow", "Pressure"))
        self.exchangeSelectCurr.setItemText(0, _translate("MainWindow", "EUR"))
        self.exchangeSelectCurr.setItemText(1, _translate("MainWindow", "USD"))
        self.exchangeSelectCurr.setItemText(2, _translate("MainWindow", "GBP"))
        self.exchangeSelectCurr.setItemText(3, _translate("MainWindow", "AUD"))
        self.exchangeSelectCurr.setItemText(4, _translate("MainWindow", "JPY"))
        self.exchangeShowBtn.setText(_translate("MainWindow", "Show"))
        self.exchangeToday.setText(_translate("MainWindow", "Today rate:"))
        self.exchangeCurrChartExch.setText(_translate("MainWindow", "Rate chart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
